name = input("Your name please:")
print("We want to know if you like programming!")
print()
print("Do you like programming" +name+ "?")
answer = input()
print("Great! You said" +answer+ "?")
print("Let's learn some Python today.")
print("But before we begin, I would like to ask you two questions.")
print("For my first question, I would like to know what you prefer, cats or dogs?")
answer =input()
print(answer+ "huh? That's a good choice, I can say I agree with you.")
print("I would like to ask you an addtional question, what is your favorite candy?")
answer = input()
print(answer+ "no way!!! Personally, I can never stop eating fruit adventure flavored tic tacs, I also like the coca cola flavor as well.")
